site_name: 陆国松的编程笔记
site_url: https://www.luguosong.com
repo_url: https://github.com/luguosong/programming-notes # 右上角仓库链接地址
repo_name: programming-notes # 右上角仓库名称
edit_uri: edit/main/code/
docs_dir: code
dev_addr: '127.0.0.1:7212'


theme:
  name: material
  language: zh
  custom_dir: overrides # 自定义主题目录
  font:
    code: Source Code Pro
  logo: https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/assert/logo.gif
  favicon: https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/assert/logo.gif
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs #导航选项卡
    - navigation.instant
    - navigation.instant.progress #导航进度
    - navigation.tracking #URL会自动更新为目录中突出显示的活动锚点
    - navigation.path #导航路径
    - navigation.top #返回顶部功能
    - navigation.indexes #索引页面
    #- navigation.prune #只有可见的导航项包含在渲染的HTML中
    #- header.autohide #自动隐藏标题栏
    - navigation.footer #底部导航
    - toc.follow #目录跟随
    - search.suggest #搜索建议
    - search.highlight #搜索结果高亮
    - search.share #搜索结果页面分享
    - content.action.edit # 代码查看按钮
    - content.action.view # 代码修改按钮
    - content.code.copy # 代码块复制按钮
    - content.code.annotate
  palette:
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
    - scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 切换到黑暗模式

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables # 表格支持
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true # 控制是在构建时使用Pygments进行高亮还是在浏览器中使用JavaScript语法高亮器进行高亮。
      anchor_linenums: true # 如果代码块包含行号，启用此设置后，行号会被包裹为锚点链接，方便你进行超链接和分享。
      auto_title: true # 自动为所有代码块添加一个标题
      line_spans: __span # 当启用此选项时，代码块的每一行都会被包裹在一个 span 元素中，这对于实现诸如行高亮等功能来说是必不可少的。
      pygments_lang_class: true # 指示Pygments添加一个CSS类来标识代码块的语言
      linenums: true # 为所有代码块添加行号
      linenums_style: pymdownx-inline # 行号样式
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: "#" #在标题末尾生成永久链接
      separator: "_" #将标题id中的空格替换成'_'
  - pymdownx.tabbed:
      alternate_style: true

extra:
  analytics:
    provider: google
    property: G-MT4W7HGBVZ
    feedback:
      title: 此页面是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 此页面很有帮助
          data: 1
          note: >-
            感谢您的反馈!
        - icon: material/emoticon-sad-outline
          name: 此页可以改进
          data: 0
          note: >-
            感谢您的反馈！请使用我们的
            <a href="https://github.com/luguosong/programming-notes/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">反馈表</a>
            帮助我们改进此页面。
  generator: true # 显示使用Material for MkDocs制作
  social: #底部社交媒体链接
    - icon: fontawesome/brands/github
      link: https://github.com/luguosong
      name: Github
    - icon: simple/wechat
      link: https://cdn.jsdelivr.net/gh/luguosong/images@master/blog-img/202404272008366.png
      name: 微信

plugins:
  - search

extra_css:
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/css/font.css
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/css/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/css/viewer.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/js/custom.js
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/js/viewer.js
  - https://cdn.jsdelivr.net/gh/luguosong/programming-notes@main/code/custom/js/viewer-js-init.js

exclude_docs: |
  node_modules

copyright: Copyright &copy; 2024 Lu Guosong #版权信息

nav:
  - 主页:
      - index.md
      - 学习资源: resources.md
  - 基础知识:
      - basic/index.md
      - 计算机组成原理:
          - basic/computer_architecture_principles/index.md
          - 计算机系统概述: basic/computer_architecture_principles/01-overview/index.md
          - 数据的表示和运算: basic/computer_architecture_principles/02-data-representation-and-operations/index.md
          - 存储器: basic/computer_architecture_principles/03-memory/index.md
          - 指令系统: basic/computer_architecture_principles/04-instruction-set/index.md
          - 中央处理器: basic/computer_architecture_principles/05-cpu/index.md
          - 总线和I/O系统: basic/computer_architecture_principles/06-bus-and-io-system/index.md
      - 操作系统:
          - basic/operating_system/index.md
      - 计算机网络:
          - basic/computer_network/index.md
          - 应用层-HTTP: basic/computer_network/application_http/index.md
      - 数据结构与算法分析:
          - basic/data-structures-and-algorithm-analysis/src/main/java/com/luguosong/index.md
          - 基础:
              - basic/data-structures-and-algorithm-analysis/src/main/java/com/luguosong/_01_foundations/index.md
              - 算法在计算中的作用: basic/data-structures-and-algorithm-analysis/src/main/java/com/luguosong/_01_foundations/_01_the_role_of_algorithms_in_computers/index.md
  - 前端:
      - front-end/index.md
      - HTML:
          - front-end/html/index.md
          - 基础: front-end/html/basic/index.md
          - HTML5: front-end/html/html5/index.md
      - CSS:
          - front-end/css/index.md
      - JavaScript:
          - front-end/js/index.md
          - JavaScript简介: front-end/js/01_Introduction_to_JavaScript/index.md
          - 词法结构: front-end/js/02_Lexical_Structure/index.md
          - 类型、值和变量: front-end/js/03_Types_Values_and_Variables/index.md
          - 表达式与操作符: front-end/js/04_Expressions_and_Operators/index.md
          - 语句: front-end/js/05_Statements/index.md
          - 对象: front-end/js/06_Objects/index.md
          - 数组: front-end/js/07_Arrays/index.md
          - 异步编程: front-end/js/13_Asynchronous_JavaScript/index.md
      - TypeScript:
          - front-end/typescript/index.md
          - 基本语法: front-end/typescript/basic/index.md
          - 工程化: front-end/typescript/engineering/index.md
      - 代码打包:
          - front-end/code_bundler/index.md
          - webpack: front-end/code_bundler/webpack/index.md
      - Vue:
          - front-end/vue/index.md
      - React:
          - front-end/react/index.md
          - 基本语法:
              - front-end/react/basic/index.md
              - 描述UI: front-end/react/basic/describing-the-ui/index.md
              - 添加交互: front-end/react/basic/adding-interactivity/index.md
              - 状态管理: front-end/react/basic/managing-state/index.md
              - 脱困机制: front-end/react/basic/escape-hatches/index.md
          - 全局状态管理:
              - front-end/react/global-state-management/index.md
              - Redux: front-end/react/global-state-management/redux/index.md
              - Mobx: front-end/react/global-state-management/mobx/index.md
          - React Router: front-end/react/react_router/index.md
          - Next.js: front-end/react/nextjs/index.md
  - Java基础:
      - java/index.md
      - JavaSE:
          - java/javase/src/main/java/com/luguosong/index.md
          - 概述: java/javase/src/main/java/com/luguosong/overview/index.md
          - 语言基础: java/javase/src/main/java/com/luguosong/basic/index.md
          - 面向对象: java/javase/src/main/java/com/luguosong/object_oriented/index.md
          - 反射: java/javase/src/main/java/com/luguosong/reflection/index.md
      - Java日志:
          - java/log/index.md
          - 基础: java/log/basic/index.md
      - Java单元测试:
          - java/test/index.md
          - JUnit5: java/test/junit/index.md
  - 服务端开发:
      - java-serve/index.md
      - Spring框架:
          - java-serve/spring/index.md
          - IOC容器: java-serve/spring/beans/index.md
          - Spring框架版本说明: java-serve/spring/spring-framework-versions/index.md
          - 控制反转: java-serve/spring/basic/index.md
          - 面向切面编程: java-serve/spring/aop/index.md
          - SSM整合: java-serve/spring/ssm/index.md
      - Web应用:
          - java-serve/web_application/index.md
          - Tomcat服务器: java-serve/web_application/tomcat/index.md
          - Servlet: java-serve/web_application/servlet/index.md
          - JSP: java-serve/web_application/jsp/index.md
          - Session和Cookie: java-serve/web_application/session_cookie/index.md
          - 过滤器和监听器: java-serve/web_application/filter_listener/index.md
          - MVC架构模式: java-serve/web_application/mvc/index.md
          - 响应式编程: java-serve/web_application/reactive/index.md
      - 数据库开发:
          - java-serve/database/index.md
          - JDBC: java-serve/database/jdbc/index.md
          - Mybatis: java-serve/database/mybatis/index.md
          - Mybatis Plus: java-serve/database/mybatis_plus/index.md
      - 认证和鉴权:
          - java-serve/authentication/index.md
      - Spring Boot:
          - java-serve/springboot/index.md
          - 基础知识: java-serve/springboot/basic/index.md
      - 分布式/微服务:
          - java-serve/distributed/index.md
          - 服务发现:
              - java-serve/distributed/service-discovery/index.md
              - Nacos: java-serve/distributed/service-discovery/nacos/index.md
          - 配置管理:
              - java-serve/distributed/configuration/index.md
              - Nacos: java-serve/distributed/configuration/nacos/nacos.md
          - 服务调用:
              - java-serve/distributed/invocation/index.md
              - RestTemplate: java-serve/distributed/invocation/rest-template/index.md
              - OpenFeign: java-serve/distributed/invocation/open-feign/index.md
          - 网关:
              - java-serve/distributed/gateway/index.md
              - Spring Cloud Gateway: java-serve/distributed/gateway/spring_cloud_gateway/index.md
  - 专项研究:
      - topics/index.md
      - 设计模式:
          - topics/design_pattern/src/main/java/com/luguosong/index.md
          - 概述: topics/design_pattern/src/main/java/com/luguosong/overview/index.md
          - 创建型模式:
              - topics/design_pattern/src/main/java/com/luguosong/creational/index.md
          - 结构型模式:
              - topics/design_pattern/src/main/java/com/luguosong/structural/index.md
              - 代理🔥: topics/design_pattern/src/main/java/com/luguosong/structural/proxy/index.md
          - 行为型模式:
              - topics/design_pattern/src/main/java/com/luguosong/behavioral/index.md
              - 责任链: topics/design_pattern/src/main/java/com/luguosong/behavioral/chain_of_responsibility/index.md
      - Maven:
          - topics/maven/index.md
          - Maven基础教程: topics/maven/base/index.md
      - Docker:
          - topics/docker/index.md
          - Docker Engine:
              - topics/docker/engine/index.md
              - 存储:
                  - topics/docker/engine/storage/index.md
                  - 数据卷(Volumes): topics/docker/engine/storage/volumes/index.md
          - Docker Build: topics/docker/build/index.md
          - Docker Compose:
              - topics/docker/compose/index.md
              - Compose文件参考:
                  - topics/docker/compose/compose-file-reference/index.md
                  - Services顶级元素: topics/docker/compose/compose-file-reference/services-top-level-elements/index.md
                  - Volumes顶层元素: topics/docker/compose/compose-file-reference/volumes-top-level-element/index.md
      - sql:
          - topics/sql/index.md
          - 环境搭建: topics/sql/environment_building.md
          - 数据库定义语言: topics/sql/ddl.md
          - 数据库操作语言: topics/sql/dml.md
          - 数据库控制语言: topics/sql/dcl.md
      - Git:
          - topics/git/index.md
          - 基础知识: topics/git/basic/index.md
      - 对象存储:
          - topics/object-store/index.md
          - MinIO: topics/object-store/minio/index.md
      - Linux:
          - topics/linux/index.md
          - 基础知识:
              - topics/linux/basic/index.md
              - 概述: topics/linux/basic/01-overview/index.md
          - 文件系统: topics/linux/file_directory/index.md
          - shell脚本: topics/linux/shell/index.md
          - 使用者管理: topics/linux/user_management/index.md
          - 系统管理员: topics/linux/system_administrator/index.md
      - 密码学:
          - topics/cryptography/src/main/java/com/luguosong/index.md
      - iText库-PDF签章:
          - topics/itext-signatures/src/main/java/com/luguosong/index.md
          - 理解数字签名的概念: topics/itext-signatures/src/main/java/com/luguosong/chapter01_understanding_the_concept_of_digital_signatures/index.md
          - PDF和数字签名: topics/itext-signatures/src/main/java/com/luguosong/chapter02_pdf_and_digital_signatures/index.md
          - 证书颁发机构、证书吊销和时间戳: topics/itext-signatures/src/main/java/com/luguosong/chapter03_certificate_authorities_certificate_revocation_and_time_stamping/index.md
          - 外部创建签名: topics/itext-signatures/src/main/java/com/luguosong/chapter04_creating_signatures_externally/index.md
          - 签名文档的验证: topics/itext-signatures/src/main/java/com/luguosong/chapter05_validation_of_signed_documents/index.md
      - 常用工具:
          - topics/tools/index.md
          - 内网穿透-frp: topics/tools/frp/index.md
  - 文档翻译:
      - document-translation/index.md
      - CSS权威指南:
          - document-translation/css-the-definitive-guide/index.md
          - CSS基础: document-translation/css-the-definitive-guide/01-css-fundamentals/index.md
      - JUnit5官方文档:
          - document-translation/junit5-user-guide/index.md
          - 概述: document-translation/junit5-user-guide/01-overview/index.md
          - 编写测试: document-translation/junit5-user-guide/02-writing-tests/index.md
      - 快捷学习Spring:
          - document-translation/spring-start-here/index.md
          - 第一部分:
              - document-translation/spring-start-here/part1/index.md
              - 现实世界中的Spring: document-translation/spring-start-here/part1/01-spring-in-the-real-world/index.md
              - 定义Bean: document-translation/spring-start-here/part1/02-defining-beans/index.md
              - Bean装配: document-translation/spring-start-here/part1/03-wiring-beans/index.md
          - 第二部分:
              - document-translation/spring-start-here/part2/index.md
      - Spring框架官方文档:
          - document-translation/spring-framework/index.md
          - 概述: document-translation/spring-framework/01-overview/index.md
          - 核心技术:
              - document-translation/spring-framework/02-core-technologies/index.md
              - IOC容器:
                  - document-translation/spring-framework/02-core-technologies/01-the-ioc-container/index.md
                  - 简介: document-translation/spring-framework/02-core-technologies/01-the-ioc-container/01-introduction/index.md
                  - 容器概述: document-translation/spring-framework/02-core-technologies/01-the-ioc-container/02-basics/index.md
      - Spring Security实战:
          - document-translation/spring-security-in-action2/index.md
          - Spring Security入门:
              - document-translation/spring-security-in-action2/part1_say_hello_to_spring_security/index.md
              - 1.安全现状: document-translation/spring-security-in-action2/part1_say_hello_to_spring_security/01_security_today/index.md
              - 2.Spring Security入门: document-translation/spring-security-in-action2/part1_say_hello_to_spring_security/02_hello/index.md
          - 配置身份认证:
              - document-translation/spring-security-in-action2/part2_configuring_authentication/index.md
              - 3.管理用户: document-translation/spring-security-in-action2/part2_configuring_authentication/03_managing_users/index.md
              - 4.管理密码: document-translation/spring-security-in-action2/part2_configuring_authentication/04_managing_passwords/index.md
              - 5.网络应用的安全性始于过滤器: document-translation/spring-security-in-action2/part2_configuring_authentication/05_begins_with_filters/index.md
              - 6.实现身份认证: document-translation/spring-security-in-action2/part2_configuring_authentication/06_implementing_authentications/index.md
          - 配置授权:
              - document-translation/spring-security-in-action2/part3_configuring_authorization/index.md
              - 7.配置端点级授权：限制访问: document-translation/spring-security-in-action2/part3_configuring_authorization/07_configuring_endpoint_level_authorization_restricting_access/index.md
          - 实施OAuth 2和OpenID Connect:
              - document-translation/spring-security-in-action2/part4_implementing_oAuth2_and_openid_connect/index.md
          - 响应式:
              - document-translation/spring-security-in-action2/part5_going_reactive/index.md
          - 测试安全配置:
              - document-translation/spring-security-in-action2/part6_testing_security_configurations/index.md
  - 英语:
      - english/index.md
      - 音标: english/phonetic_symbol/index.md
      - 新概念单词: english/new_concept_english/index.md
      - 语法: english/grammar/index.md
      - 编程词汇: english/programming_vocabulary/index.md
  - 数学:
      - math/index.md
      - Latex公式对照表: math/latex/index.md
      - 数学基础: math/basic/index.md
  - 其它:
      - other/index.md
      - IDEA使用心得: other/idea/index.md
      - 网站搭建:
          - other/website_building/index.md
          - 网站配置: other/website_building/website_building.md
          - markdown示例: other/website_building/demo.md
      - Window命令笔记: other/windows_cmd/index.md
      - MathJax:
          - other/mathjax/index.md
          - 公式代码示例: other/mathjax/formulas/index.md
      - 历史:
          - other/history/index.md
          - 中国史: other/history/chinese_history/index.md
      - PotPlayer设置: other/potplayer/index.md

