package com.luguosong.mapper;

import com.luguosong.pojo.Departments;
import java.util.List;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 23 13:46:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 23 13:46:29 CST 2024
     */
    int insert(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 23 13:46:29 CST 2024
     */
    Departments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 23 13:46:29 CST 2024
     */
    List<Departments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Tue Jul 23 13:46:29 CST 2024
     */
    int updateByPrimaryKey(Departments row);
}