spring:
  application:
    name: gateway-custom-global-filter
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: gateway-server1
          uri: lb://gateway-server1
          predicates:
            - Path=/gateway-server1/**
        - id: gateway-server2
          uri: lb://gateway-server2
          predicates:
            - Path=/gateway-server2/**
      default-filters:
        - StripPrefix=1
server:
  port: 8085
